### ISSUE TITLE
pg-native support? 

### ISSUE THREAD

**Issue by spollack** [grncdr/node-any-db-postgres#10]
Hello, 

we are running a pretty ancient version of the any-db stack, and are looking to get modern. however, we need to use pg-native not the javascript version of pg (long story, but due to bugs in the js pg that get us under stress/error conditions in production). it appears that support for native pg has been taken out. are you open to putting it back in here as an option? 

Thanks,
Seth

cc: @jshepard

**Comment by jshepard** [comment]
looks like we can still use pg-native with `process.env.NODE_PG_FORCE_NATIVE`

**Comment by spollack** [comment]
thanks @jshepard
