### ISSUE TITLE
bigint values are being returned as strings. 

### ISSUE THREAD

**Issue by nbalsamo** [grncdr/node-any-db-postgres#11]
I've read of a few ways to force pg not to parse bigint values into strings, but I'm not sure if these options are possible with any-db and any-db-postgres. 

For reference, here is one way I've read https://github.com/brianc/node-pg-types

Recasting our columns as int instead of bigint would require the modification of over 100 tables, so we are hoping to avoid that.

**Comment by grncdr** [comment]
Not sure if this is still an issue for you, but if so:

* adding a dependency on `pg` in your project
* find the OID for bigint
* follow the examples in the pg-types readme you linked to use `parseInt` on `bigint` values.

Of course, if you are storing bigint values greater than what fits in a JavaScript number, this is not going to work, and you would want to find an appropriate bignum library to parse with instead.
