### ISSUE TITLE
Param interpolation with question mark

### ISSUE THREAD

**Issue by Neamar** [grncdr/node-any-db-postgres#13]
Unlike other adapters (mysql), the "params" interpolation in query requires the user to use "$1", "$2" format.

Documentation on any-db specifies that the placeholders are supposed to be "?", any chance this can be changed?

Seems like the PG adapter won't do it anytime soon (https://github.com/brianc/node-postgres/issues/1100)

Something like, while ugly, would ensure compatibility:

```js
// This is ugly
// But why should people respect standards when they can create their own?
// https://github.com/brianc/node-postgres/issues/1100
function queryToPg(sql) {
  var counter = 1;
  var pg = sql;

  do {
    sql = pg;
    pg = sql.replace('?', '$' + counter);
    counter += 1;
  }
  while(pg !== sql);

  return pg;
}
```

**Comment by grncdr** [comment]
No, `any-db` and it's adapters do *not* touch the SQL string or parameters, they just normalize the JavaScript API for the transport & result. If you have the need to write SQL in a database independent way, layer something on top of any-db.
